### ISSUE TITLE
add README on squid cache setup, use, etc

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/config-faas-cluster#8]

**Comment by superuser-chi** [comment]
@onlyjsmith  you had added the setup on bullet 3 in start the stack section of [config-faas-cluster](https://github.com/disarm-platform/config-faas-cluster/tree/master-srv2)

**Comment by onlyjsmith** [comment]
@superuser-chi think would be useful to add something on how we use it _in functions_: i.e. adding the secret to a `stack.yml`. We've use it in the config for `fn-covariate-extractor`, but that's hard to find!

**Comment by onlyjsmith** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add instructions on what it is and how to use it, incl. with another function](https://trello.com/c/XYET0Lgu/65-add-instructions-on-what-it-is-and-how-to-use-it-incl-with-another-function)

**Comment by onlyjsmith** [comment]
Done
