### ISSUE TITLE
add README on Google logging agent

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/config-faas-cluster#9]
Incl. anything like:
- installation of agent binary
- copying/creation of configuration file
- location of log files
- creating any required folders
- etc

**Comment by superuser-chi** [comment]
i added the section on logging yesterday, please see the Logging section of [config-faas-cluster#Logging](https://github.com/disarm-platform/config-faas-cluster/tree/feature/config-traefik-access-logs)
